# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


pr: 
  branches:
    include:
      -master
      -main
      -dev
  paths:
    exclude:
      - .azure-pipelines
      - .gradle/wrapper
      - .gitignore
      - CONTRIBUTING.md
      - LICENSE
      - THIRD PARTY NOTICES
      - gradle.properties
      - gradlew
      - gradlew.bat
      - readme.md
      - settings.gradle

trigger: none # disable triggers based on commits.

variables:
  PACKAGE_NAME: 'microsoft.graph.core'
  PROJECT_PATH: '.\src\Microsoft.Graph.Core\Microsoft.Graph.Core.csproj'

pool: 
  vmImage: windows-latest

steps:
- checkout: self
  clean: true
  fetchDepth: 1

- task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
  displayName: 'Run CredScan'
  inputs:
    debugMode: false

- task: PowerShell@2
  condition: $(Build.SourceBranchName) != dev
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/Scripts/validateMavenVersion.ps1'
    pwsh: true


- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false


- task: YodLabs.O365PostMessage.O365PostMessageBuild.O365PostMessageBuild@0
  displayName: 'Graph Client Tooling pipeline fail notification'
  inputs:
    addressType: serviceEndpoint
    serviceEndpointName: 'microsoftgraph pipeline status'
    title: '$(Build.DefinitionName) failure notification'
    text: 'This pipeline has failed. View the build details for further information. This is a blocking failure. '
  condition: failed()
  enabled: true